version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-25-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Prepare dummy secret.properties
          command: |
            mkdir properties
            echo debugAnnictClientId=debugAnnictClientId >> properties/secrets.properties
            echo debugAnnictClientScret=debugAnnictClientScret >> properties/secrets.properties
            echo debugAnnictCallback=https://kgmyshin.com/annict >> properties/secrets.properties
            echo releaseAnnictClientId=releaseAnnictClientId >> properties/secrets.properties
            echo releaseAnnictClientScret=releaseAnnictClientScret >> properties/secrets.properties
            echo relaseAnnictCallback=https://kgmyshin.com/annict >> properties/secrets.properties
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - run:
          name: run Danger
          command: bundle exec danger
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results


